### ISSUE TITLE
HAY prefabs que guardan mal los valores

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#108]
* Description:
Prefabs que guardan mal los valores:
   - Particle emmiters
   - Audio sources
   - Luces (las luces no las entiendo)

* Build:
0.4.6.4
* Type:

* Steps to reproduce:

* Frequency:

Las particulas en particular son una locura

### *Partículas*:
![image](https://user-images.githubusercontent.com/25900754/56509972-bd44a300-6528-11e9-8239-0e08d3c0c9b2.png)
1
El particle shape no guarda la forma, es como si no tubiera forma
2
burst está descativado cuando no deberia
3
 la forma del burst no es la correcta
4
los valores del burst no son los correctos
5
start on play activado cuando no deberia

![image](https://user-images.githubusercontent.com/25900754/56510039-efee9b80-6528-11e9-8796-7f4d5fd402ee.png)
6. no guarda el material
7. no guarda el tick de animated sprite

![image](https://user-images.githubusercontent.com/25900754/56510069-05fc5c00-6529-11e9-806c-85bb21c85d7d.png)
Esto lo guarda bien, excepto el lifetime que es incorrecto

### *Luz*:
Lo que he hecho:
![image](https://user-images.githubusercontent.com/25900754/56509536-8621c200-6527-11e9-88a1-c26c03886cfc.png)

Prefab guardado:
![image](https://user-images.githubusercontent.com/25900754/56509558-a05ba000-6527-11e9-94fe-7a7b24ea5785.png)

### *Audio source*:
Lo que he hecho
![image](https://user-images.githubusercontent.com/25900754/56509693-f6304800-6527-11e9-88c6-3cc48c89958d.png)
Prefab guardado:

![image](https://user-images.githubusercontent.com/25900754/56509721-08aa8180-6528-11e9-94f0-ee114bc0f567.png)

**Comment by aleixgab** [comment]
Fixed particle bugs
