### ISSUE TITLE
Unable to import texture

### ISSUE THREAD

**Issue by Acaree** [JellyBitStudios/JellyBitEngine#11]
I left here a gif of importation, screen capture of imported texture import & the texture itself
https://gyazo.com/08c852312a81589d03d315c639674293
https://gyazo.com/6359dc78165450bbc27be779f5e904d4
![blood_hit_07](https://user-images.githubusercontent.com/25582060/53518958-6d220500-3ad2-11e9-8864-85d35af94d66.png)

**Comment by Jony635** [comment]
Can you confirm to us if this still happens? Otherwise we will close this issue
