### ISSUE TITLE
Bug changing transform for gameobject with mesh

### ISSUE THREAD

**Issue by cumus** [JellyBitStudios/JellyBitEngine#12]
![](https://i.gyazo.com/0e90230166e9444adc6d407925fa403f.gif)

**Comment by ValdiviaDev** [comment]
This happens when you have a rigidbody in the component with the mesh

**Comment by Jony635** [comment]
Can you confirm to us if this still happens? Otherwise we will close this issue

**Comment by ValdiviaDev** [comment]
Doesn't happen anymore, you can close it.
