### ISSUE TITLE
Engine crashes when modifying scripts in execution

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#16]
* Description:
Engine crashes when modifying scripts in excetution.
* Build:

* Type:
A

* Severity:
  - [ ] Critical
  - [ ] Major
  - [X] Minor

* Priority:
  - [ ] Urgent
  - [ ] High
  - [x] Normal
  - [ ] Low

* Steps to reproduce:
- Save script in execution
- Play game mode in the engine
- Make an input

* Frequency:
Always

![93214bef6b6cf307d2f8f44ff15aa9c6](https://user-images.githubusercontent.com/25900754/54079026-256e5b00-42d4-11e9-9790-e684925fd836.gif)

**Comment by Jony635** [comment]
When you modify a script, all its public variables are reset as the default ones and all the references are lost.
That causes some crashes inside the engine.
We are still looking into a nice solution about this theme, but honestly it is not a priority at the moment.

**Comment by Jony635** [comment]
We created a new [base issue](https://github.com/JellyBitStudios/JellyBitEngine/issues/31) to relate all the reported ones caused by this theme.
