### ISSUE TITLE
<ParticleEmiter>().Play(); not work

### ISSUE THREAD

**Issue by Siitoo** [JellyBitStudios/JellyBitEngine#18]
* Description: <ParticleEmiter>().Play(); not work in script.

* Build: 0.2.6

* Type: A

* Severity:
  - [ ] Critical
  - [X] Major
  - [ ] Minor

* Priority:
  - [ X] Urgent
  - [ ] High
  - [ ] Normal
  - [ ] Low

* Steps to reproduce: create a game object with particle emitter and call Play() in script.

* Frequency: All the time

**Comment by aleixgab** [comment]
ParticleEmiter().Play() works correctly on master
