### ISSUE TITLE
Creating a lot of default objects in play mode

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#20]
* Description:
Creating a lot of default objects in play mode when there are some errors in a script AND YOU PRESS PLAY AGAIN TO GO TO EDITION MODE.

* Build:
0.2.6

* Type:
B
* Severity:
  - [ ] Critical
  - [ ] Major
  - [X] Minor

* Priority:
  - [ ] Urgent
  - [ ] High
  - [X] Normal
  - [ ] Low

* Steps to reproduce:
- Playmode with some errors in a script
- Hit play to stop playmode

* Frequency:
Sometimes

![7952fb53cdf2ab4fdbb503b7b41f6a47](https://user-images.githubusercontent.com/25900754/54154970-65a01b80-4443-11e9-9422-bd870806e5de.gif)

**Comment by Jony635** [comment]
This is the same as [Issue 31](https://github.com/JellyBitStudios/JellyBitEngine/issues/31).
Marked as duplicate.
