### ISSUE TITLE
If you press Supr to a screen canvas the engine crashes

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#22]
* Description:
If you press Supr to a screen canvas the engine crashes

* Build:
0.2.6

* Type:
A

* Severity:
  - [ ] Critical
  - [ ] Major
  - [X] Minor

* Priority:
  - [ ] Urgent
  - [ ] High
  - [X] Normal
  - [ ] Low

* Steps to reproduce:
If you press Supr to a screen canvas the engine crashes
* Frequency:
Always

**Comment by juliamauri** [comment]
Solved
