### ISSUE TITLE
When changing the bool of obstacle avoidance in scripting, you actually change the separation

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#23]
* Description:
When changing the bool of obstacle avoidance in scripting, you actually change the separation.

* Build:
0.2.6

* Type:
B

* Severity:
  - [ ] Critical
  - [ ] Major
  - [X] Minor

* Priority:
  - [ ] Urgent
  - [ ] High
  - [X] Normal
  - [ ] Low

* Steps to reproduce:
Change the obstacle avoidance active bool via scripting.

* Frequency:
Always

**Comment by Jony635** [comment]
Fixed in next engine release
