### ISSUE TITLE
Unable to move gameobjects inside gameobjects without parent

### ISSUE THREAD

**Issue by Acaree** [JellyBitStudios/JellyBitEngine#24]
* Description: (look gif)
If game object have a parent works.

* Build: 0.2.6

* Type:

* Severity:
  - [ ] Critical
  - [ ] Major
  - [x] Minor

* Priority:
  - [ ] Urgent
  - [x] High
  - [ ] Normal
  - [ ] Low

* Steps to reproduce:
![bug](https://user-images.githubusercontent.com/25582060/54205427-9aa97e00-44d6-11e9-9e11-2a43f0ac40a5.gif)

* Frequency: Always

**Comment by Jony635** [comment]
It works on v0.2.8
