### ISSUE TITLE
Textures don't print material properly

### ISSUE THREAD

**Issue by Acaree** [JellyBitStudios/JellyBitEngine#25]
* Description: The texture are imported in that engine compilation, so isn't a .meta bug

* Build:0.2.6

* Type: Particles/Materials

* Severity:
  - [ ] Critical
  - [x] Major
  - [ ] Minor

* Priority:
  - [ ] Urgent
  - [ ] High
  - [x] Normal
  - [ ] Low

* Steps to reproduce:
![bug2](https://user-images.githubusercontent.com/25582060/54206541-c7f72b80-44d8-11e9-9d9b-e705d77f9a72.gif)

* Frequency: Always in my computer (in others is not usual)

**Comment by aleixgab** [comment]
Is fixed, you will have it on master

**Comment by Sandruski** [comment]
I fixed it. We didn't send the "light" uniform to the shader, so there was no light to illuminate the texture, thus it couldn't be seen.
