### ISSUE TITLE
In GAME MODE the in-world UI doesn't work well

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#27]
* Description:
In the Game mode release, the life bar doesn't print avobe the enemy, but like if it was a screen-UI element.

* Build:
0.2.6.1

* Type:
B

* Steps to reproduce:
Make a game mode release with a in-world UI element.

* Frequency:
Always

![image](https://user-images.githubusercontent.com/25900754/54234576-a8c7c080-450f-11e9-9beb-93c748c7ee0e.png)

**Comment by juliamauri** [comment]
Solved
