### ISSUE TITLE
Game breaks when killing an enemy and the lifebar is not working as it should

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#28]
* Description:
Regarding to this bug #27, when an enemy is hit under this conditions the executable of the Game mode crashes. 

* Build:
0.2.6.1

* Type:
A

* Steps to reproduce:
Hit the enemy with the lifebar in the specified conditions.

* Frequency:
Always

**Comment by juliamauri** [comment]
This is solved at commit:
https://github.com/JellyBitStudios/JellyBitEngine/commit/5e41bd84d0dde4be3f9b832c69c2357ff5409e8c
Ready for next engine release. Needed test it, but scipt dont work.
