### ISSUE TITLE
Engine crash when loading a scene with buildings and navmesh

### ISSUE THREAD

**Issue by JoanValiente** [JellyBitStudios/JellyBitEngine#34]
* Description: The engine crashes when I try to load a scene with buildings and navmesh. If you don't close the engine, there's no problem, the navmesh works fine, etc. But when you close it and open it again, the engine crashes the second you try to load the scene. 

* Build: 0.2.8

* Type: NavMesh / Save&Load

* Steps to reproduce: Bake a navmesh on the scene with some buildings setted as static and no walkable. Save the scene, close the engine, open it again, and try to load the scene.

* Frequency: Always

**Comment by OscarHernandezG** [comment]
Fixed in master @aleixgab
