### ISSUE TITLE
Physics collider  do not adapt to the geometry

### ISSUE THREAD

**Issue by OscarHernandezG** [JellyBitStudios/JellyBitEngine#36]
* Description:
The collision box does not adapt correctly to the geometry if it is rotated. The geometry should be included in the collision box without taking into account the rotation of the gameobject and once included, apply the rotation

* Build:
0.2.8
* Type:
Physics
* Steps to reproduce:
Rotate the GameObject and then enclose the geometry
* Frequency:
Always

**Comment by Sandruski** [comment]
Could you provide a picture of that happening?

**Comment by OscarHernandezG** [comment]
Fixed in 9eb8913bc0588d211b207e52034aee17009e6ca9
