### ISSUE TITLE
Sometimes the engine crashes when stopping playmode

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#37]
* Description:
Sometimes the engine crashes when stopping playmode

* Build:
0.2.8

* Type:
A

* Steps to reproduce:
- Play playmode
- Stop playmode

* Frequency:
1/3 of the time

**Comment by ValdiviaDev** [comment]
Still happens in v_0.3. 
Note: It can happen very often when working then not happen at all for some long time.

**Comment by ValdiviaDev** [comment]
The engine crashes here.

![image](https://user-images.githubusercontent.com/25900754/54427044-a769e400-4719-11e9-84e3-b374bc63b182.png)

**Comment by Jony635** [comment]
Should be fixed in v0.3.1. Check it when the official version releases to close the issue
