### ISSUE TITLE
Inspector position value changes in world canvas children not working as intended

### ISSUE THREAD

**Issue by Ricardogll** [JellyBitStudios/JellyBitEngine#38]
* Description: 
When moving the position of a children of world canvas via the inspector the values change and scale very quickly.

* Build:
0.2.8

* Type:
Inspector/UI

* Steps to reproduce:
Create world canvas. Add and empty children to it. Try moving x and y position in the inspector.

* Frequency:
High

![66876e9cbddfa05f560720dd675ccaab](https://user-images.githubusercontent.com/25582022/54389676-f58ed100-46a0-11e9-9a74-a5330675d2a0.gif)

**Comment by juliamauri** [comment]
It doesn't move, because the children can't go outside of parent. You need to change the size of Transforms from WorldCanvas to get a bigger canvas and move the children into it.

**Comment by juliamauri** [comment]
Or make the children smaller and move.
Rect transfrom from world, shows the info from transdform.

**Comment by juliamauri** [comment]
I test it and works correctly. Closing issue.
