### ISSUE TITLE
Textures/meshes with shaders are not visible in game mode

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#40]
* Description:
When you make the build of the game, any objects with shaders cannot be visible.

* Build:
0.3

* Type:
B

* Steps to reproduce:
- Put shaders on some material 
- Put the material on some mesh
- Make a build of the game and open it

* Frequency:
Always

**Comment by Sandruski** [comment]
Missing mesh metas in the Library folder. Now, we do export all metas belonging to meshes, so meshes can read their load settings.
