### ISSUE TITLE
In game release mode, the debug grid and axis can be seen

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#41]
* Description:
In game release mode, the debug grid and axis can be seen.

* Build:
0.3

* Type:
C

* Steps to reproduce:
- Make a build of the game and open it

* Frequency:
Always

![image](https://user-images.githubusercontent.com/25900754/54397872-40681300-46b8-11e9-9122-f98b2494259d.png)

**Comment by Sandruski** [comment]
Oh my god, we should disable debug draw when in game mode. You will have it fixed in the next build. Sorry.

**Comment by Sandruski** [comment]
(In other words, we should include grid and axis in debug draw)
