### ISSUE TITLE
Billboards aren't working

### ISSUE THREAD

**Issue by Acaree** [JellyBitStudios/JellyBitEngine#44]
* Description: El billboard son los padres

* Build: 0.3

* Type: UI

* Steps to reproduce: Put a UI image in engine. That's all

* Frequency: Always
![Elbillboardsonlospadres](https://user-images.githubusercontent.com/25582060/54450874-bcfb0000-4751-11e9-8355-7475285f4caf.gif)

**Comment by juliamauri** [comment]
I don't undertand that: El billboard son los padres. Can you show me the hiteracy of gameobjects? And the info of transforms, from parent to world canvas.

**Comment by Acaree** [comment]
El billboard son los padres was a joke <3

![Cantunderstandthat](https://user-images.githubusercontent.com/25582060/54452212-da7d9900-4754-11e9-9083-198950a5f0dc.gif)
