### ISSUE TITLE
When performing a dash in a corner Alita does a weird path

### ISSUE THREAD

**Issue by nintervik** [JellyBitStudios/JellyBitEngine#45]
* Description: when performing a dash in a corner / curved wall Alita does a weird path 
https://gyazo.com/51877eaef9339c724c5f8a42731f59e0
https://gyazo.com/40cd928265ae3693a92156435a495e58

* Build: v0.2.9.0

* Type: Scripting

* Steps to reproduce: dash against a corner or curved wall

* Frequency: always

**Comment by ValdiviaDev** [comment]
There has been a change in the dash now
