### ISSUE TITLE
Crash loading scenes

### ISSUE THREAD

**Issue by cumus** [JellyBitStudios/JellyBitEngine#5]
![](https://i.gyazo.com/51fc9223e1f9199e8405212e3d1c7098.png)

**Comment by ValdiviaDev** [comment]
Note: Scenes are charged well (some of them) before the engine crashes, but if the engine crashes for whatever reason and then you exectue the engine and try to open a scene it crashes always no matter how small the scene is.

**Comment by cumus** [comment]
Loading a saved scene while the engine runs works sometimes. When trying to load a scene after running again the engine won't allow loading and will crash.

**Comment by cumus** [comment]
load scene now also crashed here

![](https://i.gyazo.com/399c6dd13f5e00939a5a1eca2b729bc0.png)
