### ISSUE TITLE
When Alita walks near enemies her rotation goes crazy

### ISSUE THREAD

**Issue by OscarHernandezG** [JellyBitStudios/JellyBitEngine#50]
* Description:
When Alita walks near enemies her rotation goes crazy
* Build:
v0.2.9.0
* Type:
Alita
* Steps to reproduce:
Walk near an enemy
* Frequency:
Sometimes
![alitaRotation](https://user-images.githubusercontent.com/25687192/54453889-8d9bc180-4758-11e9-9a61-5fd7bc170779.gif)

**Comment by ValdiviaDev** [comment]
This is the enemies pushing the player, but it should be alright now.
