### ISSUE TITLE
You can walk through most buildings

### ISSUE THREAD

**Issue by OscarHernandezG** [JellyBitStudios/JellyBitEngine#57]
* Description:
The same that in #49  but with most of the buildings
* Build:
0.2.9.2
* Type:
Map
* Steps to reproduce:
Walk 
* Frequency:
Most of the buildings
![buildings](https://user-images.githubusercontent.com/25687192/54473794-d72df000-47dc-11e9-99ed-39fdc14d9aaf.gif)

**Comment by juliamauri** [comment]
The navmesh is present on the newest scene.
