### ISSUE TITLE
Bug with alita path

### ISSUE THREAD

**Issue by OscarHernandezG** [JellyBitStudios/JellyBitEngine#60]
* Description:
Alita path does not work as expected in the beginning of the level
* Build:
0.2.9.2
* Type:
Alita, Path
* Steps to reproduce:
Walk arround in the beginning
* Frequency:
Sometimes (some places of the map)
![alitaPathBug](https://user-images.githubusercontent.com/25687192/54473853-a601ef80-47dd-11e9-9fbb-87f5f269e608.gif)

**Comment by juliamauri** [comment]
Same as #57, the newest scene contains buildings and the nav backed. Alita don't scape.
