### ISSUE TITLE
References lost in prefabs

### ISSUE THREAD

**Issue by Acaree** [JellyBitStudios/JellyBitEngine#79]
* Description: Some references are lost whe a prefab from a gameobject is created

* Build: 0.3.3.4

* Type: Resource

* Steps to reproduce: Inside the zip we have a zip with a video to reproduce it and the assets folder used in the gif

https://drive.google.com/file/d/1cCa6OlazyQh5epyplO6d1Zm_72LP-YC-/view?usp=sharing

* Frequency: Always (but not in all references)

**Comment by Jony635** [comment]
Check if this still happens if the next engine build, I supose the version would be 0.3.5.2. 
I have changed some stuff for another bugs and I think this may have been the cause for this bug too.
