### ISSUE TITLE
Quadtree enters in a 2-years loop loading scenes

### ISSUE THREAD

**Issue by Jony635** [JellyBitStudios/JellyBitEngine#81]
* Description: Grab this Assets https://drive.google.com/open?id=1-aG_3XCrufXIPPOebtOr1aTugRlZ-7Be and load the scene mainsceneHoly.scn normally.

* Build: Last master state at 24/03/2019.

* Type: 2 years loop

* Steps to reproduce:

* Frequency: Always.

**Comment by OscarHernandezG** [comment]
Loop is not infinite, if you wait the scene will load

**Comment by Jony635** [comment]
I edit the description then, thanks!

**Comment by aleixgab** [comment]
Load scene is now faster on master
