### ISSUE TITLE
Layers mask in the inspector aren't saved in an instantiated object

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#83]
* Description:
A gameobject that is instantiated doesn't save the Layer Masks of a script assigned in the inspector.

* Build:
0.3.3.4

* Type:
B

* Steps to reproduce:
Make a prefab with a script that has a layer assigned through the inspector.

* Frequency:
Always.

![image](https://user-images.githubusercontent.com/25900754/54884587-393cc400-4e73-11e9-875a-e7470e64f50f.png)

**Comment by Jony635** [comment]
Fixed
