### ISSUE TITLE
Game objects can't set active false

### ISSUE THREAD

**Issue by Acaree** [JellyBitStudios/JellyBitEngine#91]
* Description: Active checkbox don't have any reaction

* Build: 0.3.6

* Type: Gameobject/Inspector

* Steps to reproduce:
![bug](https://user-images.githubusercontent.com/25582060/55409331-23f62280-5562-11e9-9ce1-1511acd1226c.gif)

* Frequency: Always

**Comment by Acaree** [comment]
Assets: https://drive.google.com/open?id=11ilGhKb7jT_Lw8RTh4mWfFHgjgn1tMZt

**Comment by ValdiviaDev** [comment]
The same happens with the prefabs with mesh that are put into a script from the inspector as a reference.
![image](https://user-images.githubusercontent.com/25900754/55411483-0460f900-5566-11e9-947c-36ae4d142ad2.png)
