### ISSUE TITLE
Weird bug about prefab instance GameObject references

### ISSUE THREAD

**Issue by ValdiviaDev** [JellyBitStudios/JellyBitEngine#92]
* Description:
I had a bug where I instance a prefab via code, and this prefab has a script with a reference to the GameObject of Alita. When I go into playmode the prefab instantiation works well; but when I go into playmode again, the prefab instantiates, but the reference of Alita it is not Alita but one of its children GameObjects.

* Build:
0.3.6

* Type:
B

* Steps to reproduce:
Play mode, stop the play mode and stop again.

* Frequency:
Always

![image](https://user-images.githubusercontent.com/25900754/55498921-064db980-5645-11e9-8c9e-ec7da31b3f8c.png)

**Comment by Jony635** [comment]
I will check this, but if I were you I would use a Singleton for accessing Alita.
In your main Alita script, store a "public static Alita instance" variable, and initialize it to "this" in the constructor. Then every time you want to access Alita itself you can write Alita.instance and voilà!"

**Comment by Jony635** [comment]
Fixed in the next engine release
